/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradleproject8;
import javax.swing.*;
public class App {
    
        
    

    public static void main(String[] args) {
        String input;
        String[] evenvalues = new String[2];
        
        
           for(int i = 0; i<evenvalues.length;i++){
           input = JOptionPane.showInputDialog("Enter values");
           
           evenvalues[i] = input;
           }
           JOptionPane.showMessageDialog(null,evenvalues);
    }
}
